---
- hosts: all
  become: yes
  gather-facts: yes
  tasks: 
  - name: i want to install webserver on ubuntu nodes
    apt:
      name: apache2
      state: present
    when: ansible-os-family=="debian"
  - name: i want to  start webserver on ubuntu nodes
    service:
      name: apache2
      state: started
    when: ansible-os-family=="debian"
